# Generated by Django 5.2.7 on 2026-09-28 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_date', models.DateField()),
                ('queue_position', models.PositiveIntegerField()),
                ('patients_ahead', models.PositiveIntegerField(default=0)),
                ('eta_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('CALLED', 'Called'), ('CONSULTING', 'Consulting'), ('COMPLETED', 'Completed')], default='WAITING', max_length=20)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'Queue Entry',
                'verbose_name_plural': 'Queue Entries',
                'db_table': 'queue_entries',
                'indexes': [models.Index(fields=['queue_date', 'status'], name='queue_entri_queue_d_2567ec_idx')],
                'unique_together': {('queue_date', 'appointment'), ('queue_date', 'queue_position')},
            },
        ),
    ]
