# Generated by Django 5.2.7 on 2026-09-28 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('prescription_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('COMPLETED', 'Completed')], default='STARTED', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='consultations', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='consultations', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'db_table': 'consultations',
                'indexes': [models.Index(fields=['doctor'], name='consultatio_doctor__cc7252_idx'), models.Index(fields=['patient'], name='consultatio_patient_fe04c5_idx')],
            },
        ),
    ]
