# Generated by Django 5.2.7 on 2026-09-28 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('BLOCKED', 'Blocked')], default='AVAILABLE', max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slots',
                'db_table': 'slots',
                'unique_together': {('doctor', 'slot_date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('booking_type', models.CharField(choices=[('ONLINE', 'Online'), ('WALK_IN', 'Walk-In')], max_length=20)),
                ('token_number', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('WAITING', 'Waiting'), ('CALLED', 'Called'), ('CONSULTING', 'Consulting'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='BOOKED', max_length=20)),
                ('estimated_wait_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='appointments', to='departments.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='appointments', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='appointments', to='patients.patient')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.slot')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointments',
                'indexes': [models.Index(fields=['appointment_date', 'status'], name='appointment_appoint_b9472b_idx'), models.Index(fields=['patient'], name='appointment_patient_75a4eb_idx'), models.Index(fields=['doctor', 'appointment_date'], name='appointment_doctor__4449b5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('patient', 'doctor', 'appointment_date'), name='uq_active_patient_doctor_date')],
                'unique_together': {('appointment_date', 'doctor', 'token_number')},
            },
        ),
    ]
